### ISSUE TITLE
xterm-256color support in msys2's ssh is broken.

### ISSUE THREAD

**Issue by qingxbl** [Maximus5/cygwin-connector#1]
Launching a ssh session via shell, or 
```
set TERM=xterm-256color & conemu-msys2-64.exe /usr/bin/ssh SERVER
```

It will fallback to 16 colors.

**Comment by Maximus5** [comment]
https://conemu.github.io/en/Xterm256Colors.html#xterm_256_color_mode_requirements

**Comment by qingxbl** [comment]
256color is enabled in bash, and it's working fine.

But after launching a ssh session in bash, 256color support is broken.

I'm sure the following option is enabled, and ComEnuHk.dll is injected into ssh.exe (But I don't think it's working, ssh.exe communicates with bash via pty here.)
* TrueMod (24bit color) support’ on Colors page
* ANSI X3.64 / xterm 256 colors’ on Features page
* Inject ConEmuHk’ on Features page (required for second level programs)

**Comment by Maximus5** [comment]
Try the following

* Run local bash first (where `cat AnsiColors256.ans` is working), and `ssh` from bash prompt. Any changes? Try to run `cat AnsiColors256.ans` via ssh (upload the file to remote first of course).
* Try to run `mintty -e /usr/bin/ssh SERVER`

**Comment by qingxbl** [comment]
1. I push `AnsiColor256.ans` to my server, `cat` it and it WORKS!!! But the colorscheme is still 16color.
2. mintty works fine with my color scheme.
![aaa](https://cloud.githubusercontent.com/assets/5643781/11469170/7573a338-978f-11e5-9687-ed6e09a29be8.png)

Is there something wrong with my color scheme?

**Comment by Maximus5** [comment]
What is wrong with colorscheme? Moreover, what do you bean by "colorscheme"?

**Comment by Maximus5** [comment]
> It will fallback to 16 colors

This is absolutely unclear

* https://conemu.github.io/en/BadIssue.html
* https://conemu.github.io/search.html?q=palette
* https://conemu.github.io/en/SettingsColors.html

**Comment by qingxbl** [comment]
It seems that this issue isn't belong to conemu & connector. I will figure it out myself, maybe -, -
