### ISSUE TITLE
Newline character with fish shell

### ISSUE THREAD

**Issue by mhils** [Maximus5/cygwin-connector#10]
Thanks for the great project! I'm trying to use cygwin-connector to have a fish shell on Windows using the following task:

```
set MSYSTEM=MINGW64 & C:\cygwin64\bin\conemu-cyg-64.exe -d C:\Users\user\ /usr/bin/fish -l -i
```

This generally works ok, but I always get a return symbol at the end of each command:

![image](https://cloud.githubusercontent.com/assets/1019198/13637966/5c0204a2-e60a-11e5-8d2d-9f19d95bab1a.png)

The square is a return symbol:

```
> echo 1    
1           
⏎           
> echo; echo


⏎           
> echo -n 1 
1⏎          
```

I think this is related to https://github.com/fish-shell/fish-shell/issues/789, but I have no idea which party is responsible. Any ideas?

This can be reproduced using ConEmu preview and alpha (160308) with the cygwin-connector v0.7.4 release.

**Comment by Maximus5** [comment]
Perhaps related:
http://yami-beta.hateblo.jp/entry/2016/03/16/184610

Anyway, I don't believe the problem relates to ConEmu. Ask fish author.

**Comment by eugenesvk** [comment]
@Maximus5 
Is there a chance you could respond to @ridiculousfish question in https://github.com/fish-shell/fish-shell/issues/789 so he has the information needed to fix it on his side in fish?:

> Probably the terminal emulator is behaving in a way that defeats the trick that fish uses to add this character. Does anyone have information about how the cmd terminal emulator behaves?

**Comment by jabbas** [comment]
I think this has nothing to do with fish. It looks more like when using connector \r char is subtituted by \n or \r\n.
Progressbars (like the one in pacman) are printed line by line.

When i don't use connector everything is working without a problem.

**Comment by Maximus5** [comment]
I don't see unexpected characters in current ConEmu with cygwin started under connector.
