### ISSUE TITLE
Interactive program not detecting connector as tty

### ISSUE THREAD

**Issue by maoueh** [Maximus5/cygwin-connector#11]
It's more a question than an issue per se, as it might actually be how it's supposed to work.

Program like `npm` that decides to colorized output based on the detection that the connected terminal is actually an interactive one does not detect the connector as such.

So, for example, running `npm install -g gulp` using the connector does not print colorized output nor the progress bar which is interactive. Executing plain bash inside ConEmu without the connector works correctly.

So question is, is it how it's supposed to work? Is it something that would be solvable as I'm ready to invest time on this issue as right now, I switch between two consoles (or use msys2 `winpty` to trick the running program).

Regards,
Matt

**Comment by Maximus5** [comment]
Work on connector is not fished yet. In future I plan to do automatic switch from POSIX pty to Windows console. I suppose npm is "native console application"?
At the moment, winpty is the workaround.

**Comment by maoueh** [comment]
To be precise, `npm` is a `Node.js` script invoked using a native console application `node.exe`, yes.

I would that auto-switch work exactly? You would check invoked child program and determined if it's a `POSIX` one (for example, those linked to `msys-2.0.dll`) and process them differently?

**Comment by Maximus5** [comment]
> You would check invoked child program and determined if it's a POSIX one (for example, those linked to msys-2.0.dll) and process them differently?

Yes. Also, connector would be started automatically for cygwin/msys applications.

**Comment by Maximus5** [comment]
By the way, at the moment you may try this
```
ConEmuC -std -c npm install -g gulp
```
Or even create an alias (bash alias of course).

But I think preferrable way nowadays is WSL.
