### ISSUE TITLE
Support for wslbridge?

### ISSUE THREAD

**Issue by fpqc** [Maximus5/cygwin-connector#14]
Hiya Maximus5.  There is a bridge program that bridges from cygwin to WSL https://github.com/rprichard/wslbridge that works perfectly inside of mintty.  I assumed that the cygwin connector would be able to then do a further bridge from conemu to cygwin, and by using both bridges, we could get full xterm-256color support in in ConEMU and WSL bash.

However, when I tried to run wslbridge using the cygwin-connector, it says the background process died and won't run.  Any idea what's going on?

**Comment by Maximus5** [comment]
Actually, it just works. Perhaps you've installed wslbridge improperly.

**Comment by fpqc** [comment]
@maximus5 Do you have a suggested configuration?

**Comment by Maximus5** [comment]
https://conemu.github.io/en/BashOnWindows.html#true-color

**Comment by fpqc** [comment]
Thanks! Going to do it now!
