### ISSUE TITLE
msys 64 connector cannot launch bash session

### ISSUE THREAD

**Issue by iongion** [Maximus5/cygwin-connector#16]
I have a task command:
```
set MSYSTEM=MINGW64 & set HOME=/home/worker & set TERM=xterm-256color & C:\Applications\Conemu\terminals\conemu-msys2-64.exe --verbose -d W:\SDKs\msys2
```

The output that I get is:
```
{PID:16788} declaring TERM: `xterm-256color` (was: `xterm-256color `)
{PID:16788} current $HOME is `/home/worker `
{PID:16788} 0: isatty()=1; pgrp=16788; ttyname()=`/dev/cons0`
{PID:16788} 1: isatty()=1; pgrp=16788; ttyname()=`/dev/cons0`
{PID:16788} 2: isatty()=1; pgrp=16788; ttyname()=`/dev/cons0`
{PID:16788} calling fork (pgid=16788)
{PID:16788} child pid=16496 pgid=16788 was created (ourpgid=16788)
{PID:16788} PTY was created: `/dev/pty0`; Child PID:16496
{PID:16788} 0: isatty()=1; pgrp=16788; ttyname()=`/dev/cons0`
{PID:16788} 1: isatty()=1; pgrp=16788; ttyname()=`/dev/cons0`
{PID:16788} 2: isatty()=1; pgrp=16788; ttyname()=`/dev/cons0`
{PID:16788} raising SIGUSR1 in pid=16496
{PID:16496} child created (pgid=16496)
{PID:16496} child process wating for SIGUSR1 (pgid=16496)
{PID:16496} SIGUSR1 received
{PID:16496} child process continues after 0 ms (SIGUSR1=1)
{PID:16496} ttyname(1)=`/dev/pty0`
{PID:16496} ttyname(1)=`/dev/pty0`
{PID:16496} 0: isatty()=1; pgrp=16496; ttyname()=`/dev/pty0`
{PID:16788} SIGUSR1 received
{PID:16496} 1: isatty()=1; pgrp=16496; ttyname()=`/dev/pty0`
{PID:16496} 2: isatty()=1; pgrp=16496; ttyname()=`/dev/pty0`
{PID:16496} raising SIGUSR1 in pid=16788
{PID:16496} shell: `/usr/bin/bash` `-l` `-i`
{PID:16496}   dir: `/cygdrive/W/SDKs/msys2`
{PID:16496} failed to run shell (2): No such file or directory
{PID:16788} read(3) failed (5): Input/output error
{PID:16788} pty_fd set to -1
{PID:16788} pid=16496 was terminated, exitcode=2
{PID:16788} Stopping our threads
{PID:16788} normal exit from main
```
And there is a proper msys at that location:
![image](https://cloud.githubusercontent.com/assets/867609/19523818/f93fff1e-961b-11e6-9d26-3d13b71d8374.png)

I see that the `/cygdrive` prefix to drives is present, but it is not valid, the `/etc/fstab` of msys specifically mentions that it removes the `/cygdrive` prefix, it is the default fstab configuration of msys:
```
# For a description of the file format, see the Users Guide
# http://cygwin.com/cygwin-ug-net/using.html#mount-table
# DO NOT REMOVE NEXT LINE. It remove cygdrive prefix from path
none / cygdrive binary,posix=0,noacl,user 0 0
```

Nevertheless, I see that the directory can be changed and I put it to `/W/SDKs/msys2` and `W:\SDKs\msys2`, none works when passing as argument:

```
set MSYSTEM=MINGW64 & set HOME=/home/worker & set TERM=xterm-256color & C:\Applications\Conemu\terminals\conemu-msys2-64.exe --verbose -d W:\SDKs\msys2
```

What can I do ? It always ends up in ```failed to run shell (2): No such file or directory```

**Comment by Maximus5** [comment]
How do you think connector could understand where is your "root"?
Switch `-d` is intended for *working directory*, not a toolset location.
Either move connector to bin folder, or specify **full** path to shell using your msys namespace.

**Comment by Maximus5** [comment]
And try to run connector without prepended set-s.
Fresh msys2 x64 and connector runs without problem if bin exists in path.

**Comment by iongion** [comment]
- Just did this, fresh msys installation, dropped connector as instructed
- Set-up a task in ConEmu:
```
set MSYSTEM=MINGW64 & W:\SDKs\msys2\usr\bin\conemu-msys2-64.exe
```
- Ran `pygtk-demo` to know if there is no issue with msys bootstrap, none so far.
- Ran `pip install --upgrade pip` - no SSL error, so all perfect!

Thank you! The dropping inside msys did it! No words!
