### ISSUE TITLE
zsh prompt '%' after each command when using connector

### ISSUE THREAD

**Issue by tete1030** [Maximus5/cygwin-connector#19]
Hi,
My ConEmu version is 161022[64], cygwin-connector version is 0.7.4, task commands are:
**with connector:**

> E:\cygwin64\bin\conemu-cyg-64.exe E:\cygwin64\bin\wslbridge.exe -t "zsh" -new_console:d:%USERPROFILE% -new_console:np -new_console:t:"WSL zsh"

**without connector:**

> E:\cygwin64\bin\wslbridge.exe -t "zsh" -new_console:d:%USERPROFILE% -new_console:np -new_console:t:"WSL zsh"

In the following image you can see when connector is used, zsh prompts a '%' symbol after each command.

![7](https://cloud.githubusercontent.com/assets/4312115/19828744/1d29fc26-9e01-11e6-88d4-6ef3a43e836e.png)

I think this issue might be related to https://github.com/Maximus5/cygwin-connector/issues/10, but this problem is about zsh not fish, and when the connector is not used, the '%' is gone.

**Comment by selfuryon** [comment]
+1 I have the same issue

**Comment by selfuryon** [comment]
Going to some deeper:
Maybe problem in TERM enviroment variable...
![1](https://cloud.githubusercontent.com/assets/2993917/21595971/e5ecafe6-d155-11e6-8e3f-2f3a34ad056c.png)

**Comment by selfuryon** [comment]
After upgrading conemu to 170118 symbol  "%" disappears from the screen. So problem was in conemu?..
