### ISSUE TITLE
example

### ISSUE THREAD

**Issue by pcause** [Maximus5/cygwin-connector#2]
I can't figure out how /when to run this.  I start msys2 using:

c:\\tools\conemu\conemu64.exe  -cmd "set WD=c:\tools\msys64" & set MSYSTEM=MINGW64 & c:\tools\msys64\usr\bin\bash.exe --login -i

This works fine but the terminal emulation doesn't work fully.  I assume this fixes it but can't figure out how to run this before bash starts.  can you provide an example or a bit more in the way of docs?

**Comment by Maximus5** [comment]
https://conemu.github.io/en/CygwinMsysConnector.html

**Comment by pcause** [comment]
thanks.  figured out.
