### ISSUE TITLE
Zsh in tmux in connector is broken

### ISSUE THREAD

**Issue by ecx86** [Maximus5/cygwin-connector#22]
### Versions

ConEmu build: 170805 x64
OS version: Windows 1607 x64 14393.0 (LTSB)
Used shell version zsh in tmux, in wslbridge
wslbridge: from wsltty 1.7.9
Connector: v1.2, x64 cygwin

### Problem description
Output in zsh above the current prompt is invisible.

### Steps to reproduce

1. Start ConEmu using task:
```
@echo off
call SetEscChar
echo %ESC%[9999H
set PATH="%~dp0;%PATH%"
"%~dp0..\conemu-cyg-64.exe" "%~dp0\wslbridge.exe"
```
Task: `cmd /c run.cmd -new_console:h9999 -new_console:p5nam:/mnt`

2. Start tmux.
3.  Start zsh.
(Blank .zshrc and .tmux.conf)

The problem occurs when zsh is run through the ConEmu connector and wslbridge but does not occur when run through wslbridge only. The issue does not occur in zsh only. It occurs when running zsh in tmux. The issue does not occur without the connector, the connector seems to be the issue. Also running bash in zsh in tmux in wslbridge in connector works normally. I don't know why zsh is weird.

### Actual results
Output in zsh appears for a brief moment and then immediately disappears. The prompt moves down as expected, however the output above it does not show up. It remains in scrollback. Interestingly enough the output begins to show when it reaches the bottom of the buffer, but only then.

### Expected results
Output in zsh should be visible.

### Additional files

[screenshot](http://i.imgur.com/lWiUe13.png)
[logs](https://transfer.sh/mjxkZ/conemu%20logs.zip)

**Comment by ecx86** [comment]
Update: I've hacked together a solution by prepending `%{\e[9999H%}` to my zsh prompt for when I use wslbridge.

**Comment by Maximus5** [comment]
Connector and wslbridge are now integrated into ConEmu distro.

On your screenshot I don't see [StatusBar](https://conemu.github.io/en/StatusBar.html), I'm interested in columns 'Terminal modes', 'Console visible rectangle' and 'Console buffer size'.

When you run tmux the height of ConEmu (you set it to `9999` by `-new_console:h9999`) is disabled - tmux process all backscroll internally.

**Comment by Maximus5** [comment]
One more question - is there a text or  it is just invisible (black on black). You may check that by selecting console contents.

**Comment by ecx86** [comment]
Selecting in tmux makes the output come back (??). Very strange.

Modes: XACM

**Comment by ecx86** [comment]
This issue is misleading.
