### ISSUE TITLE
French (non-US?) keyboard, AltGr and Git-bash

### ISSUE THREAD

**Issue by techexo** [Maximus5/cygwin-connector#23]
Hello,

I have troubles using ConEmu with its conemu-msys2-64 connector and a French keyboard (i.e. probably any non-US keyboard with an AltGr key instead of "right Alt").

Running directly from ConEmu the `%Git%/usr/bin/bash.exe` works like a charm, but without 256 colors. Using the last version of ConEmu, the `{{Bash::Git Bash}}` task (that uses conemu-msys2-64 by default) displays all the 256 colors (!!!), but some of the [AltGr]+key combinations don't work. 

Thus, the following keys are not detected and/or displayed by bash via the connector: [AltGr]+[2] (~), [AltGr]+[5] ([), [AltGr]+[8] (\\) and [AltGr]+[°] (]).
Even more disturbing, is that using `./conemu-msys2-64.exe --keys` either in `cmd.exe` or in "standalone" `bash.exe` and typing the same keys show what is expected `<x7E:~><x5B:[><x5C:\><x5D:]`

Consequently, as `bash` works very well alone (in 8 colors) and as `conemu-msys2-64` seems to recognize the keys, there should be some issue in the communication between the two, that I did not succeed to solve on my own. 

Windows 7 64 bits
ConEmu 170730 [64] Alpha
Git 2.14.0 ; git-bash --version = 4.4.12
conemu-msys2-64 v1.2

Thank you very much in advance !

**Comment by Maximus5** [comment]
Duplicate: https://github.com/Maximus5/ConEmu/issues/1220
