### ISSUE TITLE
Ansi colors 256 cygwin

### ISSUE THREAD

**Issue by lv-gh** [Maximus5/cygwin-connector#25]
**ConEmu & Connector version:**
> ConEmu 171226 [64] Startup Info
OsVer: 10.0.16299.x64, Product: 1, SP: 0.0, Suite: 0x100, SM_SERVERR2: 0

>`conemu-cyg-64.exe --version`
ConEmu cygwin/msys connector version 1.2.4

**Cygwin version:**
> `$ uname -r`
2.9.0(0.318/5/3)

**Cygwin Task contents:**
> set CHERE_INVOKING=1 & set "PATH=%ConEmuDrive%\cygwin64\bin;%PATH%" & %ConEmuBaseDirShort%\conemu-cyg-64.exe -new_console:p %ConEmuDrive%\cygwin64\bin\bash.exe --login -i -new_console:C:"%ConEmuDrive%\cygwin64\Cygwin.ico"

`$ cat AnsiColors256.ans`

![ansi256](https://user-images.githubusercontent.com/3296959/34389588-238110e2-eb43-11e7-8fdd-1726c6bfc5a0.PNG)

**Comment by Maximus5** [comment]
https://conemu.github.io/en/Xterm256Colors.html

**Comment by lv-gh** [comment]
Still unclear and very confusing to me: cat AnsiColors256.ans (https://conemu.github.io/en/CygwinMsysConnector.html) doesn't work as it's promoted (outdated info?) and https://conemu.github.io/en/Xterm256Colors.html should give an answer what it won't work? (BTW, all xterm256 mode requirements are satisfied, except "Turn off scrolling")

**Comment by lv-gh** [comment]
Ah, sorry: works with disabled scrolling buffer (-cur_console:h). But manual page (https://conemu.github.io/en/CygwinMsysConnector.html) should explicitly denote/highlight that (all xterm256 mode requirements)
