### ISSUE TITLE
msys connector doesn't propagate ctrl-c signal correctly

### ISSUE THREAD

**Issue by akrieger** [Maximus5/cygwin-connector#29]
In the same setup as https://github.com/Maximus5/cygwin-connector/issues/28, if I try to ctrl-c the buck build via the connector, the root process terminates but child processes do not. If I ctrl-c while directly running bash.exe, everything terminates as expected.

**Comment by Maximus5** [comment]
Already reported on the main site

**Comment by akrieger** [comment]
I'm confused. I looked on the main site and saw the section about ctrl-c issues, but this seems specific to the connector. Without the connector, ctrl-c works fine. With the connector, ctrl-c breaks.

Do you mean it's just impossible to fix in the connector for the same reason ctrl-c issues happen in other cases?

**Comment by akrieger** [comment]
Or do you mean https://github.com/Maximus5/ConEmu/issues/1576 ?

**Comment by Maximus5** [comment]
Exactly
