### ISSUE TITLE
Incompatibility with the latest ConEmu release

### ISSUE THREAD

**Issue by ferenczy** [Maximus5/cygwin-connector#31]
### Versions

ConEmu build: 180626 x64
OS version: Windows 7 x64
Used shell version: Cygwin 2.11.1
Cygwin connector version: 1.2

### Problem description

I'm experiencing various issues with the Cygwin connector, mainly when I'm using [screen](https://www.gnu.org/software/screen/manual/screen.html) (a window multiplexer) and I noticed that the latest ConEmu release is distributed with some very old Cygwin connector - it's version 0.4 - so I have downloaded the [latest release](https://github.com/Maximus5/cygwin-connector/releases/tag/v1.2) from the connector's repo but when I try to use it, ConEmu complains with the following error:

    RequestTermConnector failed

### Steps to reproduce

1. Unpack the latest ConEmu release (180626)
2. Replace Cygwin connector executables with the latest release (1.2)
3. Execute ConEmu

### Actual results

The error message `RequestTermConnector failed` is displayed.

### Expected results

ConEmu is properly running.

**Comment by Maximus5** [comment]
> Replace Cygwin connector executables with the latest release (1.2)

What?? Latest Connector release is shipped with ConEmu!

**Comment by Maximus5** [comment]
> Replace Cygwin connector executables with the latest release (1.2)

What?? Latest Connector release is shipped with ConEmu!

**Comment by ferenczy** [comment]
Sorry, my bad, I had the ConEmu's Cygwin connector shadowed by some old one which was earlier in `PATH` so I was getting:

    $ conemu-cyg-64 --version
    ConEmu cygwin/msys connector version 0.4

I have removed the old one and now it's reporting the version 1.2.5, so I guess it's correct.

In that case I'll create new issues for problems I'm observing, I think we may close this one.
