### ISSUE TITLE
AltGr not working properly, x1B addition ?

### ISSUE THREAD

**Issue by LordFPL** [Maximus5/cygwin-connector#4]
Hello,

I have a problem with msys2 & cygwin connector : i can't do many altgr character (azerty keyboard)... 

* Without connector : 
 * Task (default) : ```set CHERE_INVOKING=1 & C:\msys64\usr\bin\sh.exe --login -i -new_console:C:"C:\msys64\msys2.ico"```
 * If i try to make a "@" : 
```
$ conemu-msys2-64.exe --keys
ConEmu cygwin/msys connector version 0.7
Starting raw conin reader, press Ctrl+C to stop
<x40:@>
```

* With connector : 
 * Task : ```set CHERE_INVOKING=1 & C:\msys64\usr\bin\conemu-msys2-64.exe -new_console:C:"C:\msys64\msys2.ico"```
 * If i try to make a "@" : 
```
$ conemu-msys2-64.exe --keys
ConEmu cygwin/msys connector version 0.7
Starting raw conin reader, press Ctrl+C to stop
<x1B><x40:@>
```

Why there is ```<x1B>``` addition ?

**Comment by Maximus5** [comment]
What keyboard layout do you use?

**Comment by LordFPL** [comment]
Azerty (french keyboard) with fr_FR.UTF-8 locale

**Comment by abesada** [comment]
Same issue wit the last connector 0.7 and 0.7.1
$ locale
LANG=es_ES.UTF-8
LC_CTYPE="es_ES.UTF-8"
LC_NUMERIC="es_ES.UTF-8"
LC_TIME="es_ES.UTF-8"
LC_COLLATE="es_ES.UTF-8"
LC_MONETARY="es_ES.UTF-8"
LC_MESSAGES="es_ES.UTF-8"
LC_ALL=

**Comment by Maximus5** [comment]
It's not a connector's, but ConEmu's issue.

**Comment by LordFPL** [comment]
It's a know issue ? Any workaround or issue number ? Do you want a new issue for that in conemu project ?

**Comment by Maximus5** [comment]
Just wait for fix

**Comment by LordFPL** [comment]
I just try last release (151222) : it's ok !!! :) Thx ! :)
