### ISSUE TITLE
zsh: can't set tty pgrp: operation not permitted

### ISSUE THREAD

**Issue by agross** [Maximus5/cygwin-connector#5]
I'm trying to use Cygwin zsh with your new connector. First off, thanks for creating it, was looking forward to improved Cygwin integration.

My ConEmu task starts a new zsh session like this:
```
c:\Cygwin\bin\conemu-cyg-32.exe /usr/bin/zsh --interactive --login
```

My zsh startup initializes the completion system (`compinit`) and also [attempts to run `ssh-agent` unless it already has been started](https://github.com/agross/dotfiles/blob/master/profiles/cygwin/zsh/zsh/plugins/ssh-agent.plugin.zsh). While these actions are performed, the shell prints output like this:

```
compinit:534: can't set tty pgrp: operation not permitted
/home/agross/.zsh/plugins/ssh-agent.plugin.zsh:68: can't set tty pgrp: operation not permitted
zsh: can't set tty pgrp: operation not permitted
```

I'm running ConEMU 151217 alpha, connection 0.7.1 and Cygwin latest.

**Comment by Dobz** [comment]
Same issue here using ConEmu 151217 and version 0.7.1 of the connector.

**Comment by Maximus5** [comment]
What about mintty?

**Comment by Dobz** [comment]
The error doesn't happen in mintty, nor in ConEmu without the connector.

**Comment by Maximus5** [comment]
https://github.com/Maximus5/cygwin-connector/releases/tag/v0.7.2

**Comment by Dobz** [comment]
Thanks, seems to be good now.

**Comment by agross** [comment]
Thanks! :+1:
